export const board = {
  dimension: 5,
  table: {
    0: {value: 1, focus: false, active: false, image: 'airplane.jpg', valueExpected: 1},
    1: {value: 2, focus: false, active: false, image: 'airplane.jpg', valueExpected: 2},
    2: {value: 3, focus: false, active: false, image: 'airplane.jpg', valueExpected: 3},
    3: {value: 4, focus: false, active: false, image: 'airplane.jpg', valueExpected: 4},
    4: {value: 5, focus: false, active: false, image: 'airplane.jpg', valueExpected: 5},
    5: {value: 6, focus: false, active: false, image: 'airplane.jpg', valueExpected: 6},
    6: {value: 7, focus: false, active: false, image: 'airplane.jpg', valueExpected: 7},
    7: {value: 8, focus: false, active: false, image: 'airplane.jpg', valueExpected: 8},
    8: {value: 9, focus: false, active: false, image: 'airplane.jpg', valueExpected: 9},
    9: {value: 10, focus: false, active: false, image: 'airplane.jpg', valueExpected: 10},
    10: {value: 11, focus: false, active: false, image: 'airplane.jpg', valueExpected: 11},
    11: {value: 12, focus: false, active: false, image: 'airplane.jpg', valueExpected: 12},
    12: {value: 13, focus: false, active: false, image: 'airplane.jpg', valueExpected: 13},
    13: {value: 14, focus: false, active: false, image: 'airplane.jpg', valueExpected: 14},
    14: {value: 15, focus: false, active: false, image: 'airplane.jpg', valueExpected: 15},
    15: {value: 16, focus: false, active: false, image: 'airplane.jpg', valueExpected: 16},
    16: {value: 17, focus: false, active: false, image: 'airplane.jpg', valueExpected: 17},
    17: {value: 18, focus: false, active: false, image: 'airplane.jpg', valueExpected: 18},
    18: {value: 19, focus: false, active: false, image: 'airplane.jpg', valueExpected: 19},
    19: {value: 20, focus: false, active: false, image: 'airplane.jpg', valueExpected: 20},
    20: {value: 21, focus: false, active: false, image: 'airplane.jpg', valueExpected: 21},
    21: {value: 22, focus: false, active: false, image: 'airplane.jpg', valueExpected: 22},
    22: {value: 23, focus: false, active: false, image: 'airplane.jpg', valueExpected: 23},
    23: {value: 24, focus: false, active: false, image: 'image.png', valueExpected: 0},
    24: {value: 0, focus: false, active: false, image: 'airplane.jpg', valueExpected: 24}  // Asume que 0 es el espacio vacío para mover
  }
};
