export const board = {
  dimension: 5,
  table: {
    0: { focus: false, active: false, image: 'airplane.jpg', valueExpected: 0},
    1: { focus: false, active: false, image: 'airplane.jpg', valueExpected: 1},
    2: { focus: false, active: false, image: 'airplane.jpg', valueExpected: 2},
    3: { focus: false, active: false, image: 'airplane.jpg', valueExpected: 3},
    4: { focus: false, active: false, image: 'airplane.jpg', valueExpected: 4},
    5: { focus: false, active: false, image: 'airplane.jpg', valueExpected: 5},
    6: { focus: false, active: false, image: 'airplane.jpg', valueExpected: 6},
    7: { focus: false, active: false, image: 'airplane.jpg', valueExpected: 7},
    8: { focus: false, active: false, image: 'airplane.jpg', valueExpected: 8},
    9: { focus: false, active: false, image: 'airplane.jpg', valueExpected: 9},
    10: { focus: false, active: false, image: 'airplane.jpg', valueExpected: 10},
    11: { focus: false, active: false, image: 'airplane.jpg', valueExpected: 11},
    12: { focus: false, active: false, image: 'airplane.jpg', valueExpected: 12},
    13: { focus: false, active: false, image: 'airplane.jpg', valueExpected: 13},
    14: { focus: false, active: false, image: 'airplane.jpg', valueExpected: 14},
    15: { focus: false, active: false, image: 'airplane.jpg', valueExpected: 15},
    16: { focus: false, active: false, image: 'airplane.jpg', valueExpected: 16},
    17: { focus: false, active: false, image: 'airplane.jpg', valueExpected: 17},
    18: { focus: false, active: false, image: 'airplane.jpg', valueExpected: 18},
    19: { focus: false, active: false, image: 'airplane.jpg', valueExpected: 19},
    20: { focus: false, active: false, image: 'airplane.jpg', valueExpected: 20},
    21: { focus: false, active: false, image: 'airplane.jpg', valueExpected: 21},
    22: { focus: false, active: false, image: 'airplane.jpg', valueExpected: 22},
    23: { focus: false, active: false, image: 'image.png', valueExpected: 24},
    24: { focus: false, active: false, image: 'airplane.jpg', valueExpected: 23}  // Asume que 0 es el espacio vacío para mover
  }
};
