export const board5 = {
  dimension: 5,
  image: 'airplane.jpg',
  blankImage: 'image.png',
  initialTable: {
    0: {
      positionImage: '0% 0%',
      focus: false,
      isBlank: false,
      active: false,
      valueExpected: 0,
    },
    1: {
      positionImage: '25% 0%',
      focus: false,
      isBlank: false,
      active: false,
      valueExpected: 1,
    },
    2: {
      positionImage: '50% 0%',
      focus: false,
      isBlank: false,
      active: false,
      valueExpected: 2,
    },
    3: {
      positionImage: '75% 0%',
      focus: false,
      isBlank: false,
      active: false,
      valueExpected: 3,
    },
    4: {
      positionImage: '100% 0%',
      focus: false,
      isBlank: false,
      active: false,
      valueExpected: 4,
    },
    5: {
      positionImage: '0% 25%',
      focus: false,
      isBlank: false,
      active: false,
      valueExpected: 5,
    },
    6: {
      positionImage: '25% 25%',
      focus: false,
      isBlank: false,
      active: false,
      valueExpected: 6,
    },
    7: {
      positionImage: '50% 50%',
      focus: false,
      isBlank: false,
      active: false,
      valueExpected: 12,
    },
    8: {
      positionImage: '75% 25%',
      focus: false,
      isBlank: false,
      active: false,
      valueExpected: 8,
    },
    9: {
      positionImage: '100% 25%',
      focus: false,
      isBlank: false,
      active: false,
      valueExpected: 9,
    },
    10: {
      positionImage: '0% 50%',
      focus: false,
      isBlank: false,
      active: false,
      valueExpected: 10,
    },
    11: {
      positionImage: '25% 50%',
      focus: false,
      isBlank: false,
      active: false,
      valueExpected: 11,
    },
    12: {
      positionImage: '50% 25%',
      focus: false,
      isBlank: false,
      active: false,
      valueExpected: 7,
    },
    13: {
      positionImage: '75% 50%',
      focus: false,
      isBlank: false,
      active: false,
      valueExpected: 13,
    },
    14: {
      positionImage: '100% 50%',
      focus: false,
      isBlank: false,
      active: false,
      valueExpected: 14,
    },
    15: {
      positionImage: '0% 75%',
      focus: false,
      isBlank: false,
      active: false,
      valueExpected: 15,
    },
    16: {
      positionImage: '25% 75%',
      focus: false,
      isBlank: false,
      active: false,
      valueExpected: 16,
    },
    17: {
      positionImage: '50% 75%',
      focus: false,
      isBlank: false,
      active: false,
      valueExpected: 17,
    },
    18: {
      positionImage: '75% 75%',
      focus: false,
      isBlank: false,
      active: false,
      valueExpected: 18,
    },
    19: {
      positionImage: '100% 75%',
      focus: false,
      isBlank: false,
      active: false,
      valueExpected: 19,
    },
    20: {
      positionImage: '0% 100%',
      focus: false,
      isBlank: false,
      active: false,
      valueExpected: 20,
    },
    21: {
      positionImage: '25% 100%',
      focus: false,
      isBlank: false,
      active: false,
      valueExpected: 21,
    },
    22: {
      positionImage: '50% 100%',
      focus: false,
      isBlank: false,
      active: false,
      valueExpected: 22,
    },
    23: {
      positionImage: '100% 100%',
      focus: false,
      isBlank: true,
      active: false,
      valueExpected: 24,
    },
    24: {
      positionImage: '75% 100%',
      focus: false,
      isBlank: false,
      active: false,
      valueExpected: 23,
    }, // Asume que 0 es el espacio vacío para mover
  },
  table: {
    0: {
      positionImage: '0% 0%',
      focus: false,
      isBlank: false,
      active: false,
      valueExpected: 0,
    },
    1: {
      positionImage: '25% 0%',
      focus: false,
      isBlank: false,
      active: false,
      valueExpected: 1,
    },
    2: {
      positionImage: '50% 0%',
      focus: false,
      isBlank: false,
      active: false,
      valueExpected: 2,
    },
    3: {
      positionImage: '75% 0%',
      focus: false,
      isBlank: false,
      active: false,
      valueExpected: 3,
    },
    4: {
      positionImage: '100% 0%',
      focus: false,
      isBlank: false,
      active: false,
      valueExpected: 4,
    },
    5: {
      positionImage: '0% 25%',
      focus: false,
      isBlank: false,
      active: false,
      valueExpected: 5,
    },
    6: {
      positionImage: '25% 25%',
      focus: false,
      isBlank: false,
      active: false,
      valueExpected: 6,
    },
    7: {
      positionImage: '50% 50%',
      focus: false,
      isBlank: false,
      active: false,
      valueExpected: 12,
    },
    8: {
      positionImage: '75% 25%',
      focus: false,
      isBlank: false,
      active: false,
      valueExpected: 8,
    },
    9: {
      positionImage: '100% 25%',
      focus: false,
      isBlank: false,
      active: false,
      valueExpected: 9,
    },
    10: {
      positionImage: '0% 50%',
      focus: false,
      isBlank: false,
      active: false,
      valueExpected: 10,
    },
    11: {
      positionImage: '25% 50%',
      focus: false,
      isBlank: false,
      active: false,
      valueExpected: 11,
    },
    12: {
      positionImage: '50% 25%',
      focus: false,
      isBlank: false,
      active: false,
      valueExpected: 7,
    },
    13: {
      positionImage: '75% 50%',
      focus: false,
      isBlank: false,
      active: false,
      valueExpected: 13,
    },
    14: {
      positionImage: '100% 50%',
      focus: false,
      isBlank: false,
      active: false,
      valueExpected: 14,
    },
    15: {
      positionImage: '0% 75%',
      focus: false,
      isBlank: false,
      active: false,
      valueExpected: 15,
    },
    16: {
      positionImage: '25% 75%',
      focus: false,
      isBlank: false,
      active: false,
      valueExpected: 16,
    },
    17: {
      positionImage: '50% 75%',
      focus: false,
      isBlank: false,
      active: false,
      valueExpected: 17,
    },
    18: {
      positionImage: '75% 75%',
      focus: false,
      isBlank: false,
      active: false,
      valueExpected: 18,
    },
    19: {
      positionImage: '100% 75%',
      focus: false,
      isBlank: false,
      active: false,
      valueExpected: 19,
    },
    20: {
      positionImage: '0% 100%',
      focus: false,
      isBlank: false,
      active: false,
      valueExpected: 20,
    },
    21: {
      positionImage: '25% 100%',
      focus: false,
      isBlank: false,
      active: false,
      valueExpected: 21,
    },
    22: {
      positionImage: '50% 100%',
      focus: false,
      isBlank: false,
      active: false,
      valueExpected: 22,
    },
    23: {
      positionImage: '100% 100%',
      focus: false,
      isBlank: true,
      active: false,
      valueExpected: 24,
    },
    24: {
      positionImage: '75% 100%',
      focus: false,
      isBlank: false,
      active: false,
      valueExpected: 23,
    }, // Asume que 0 es el espacio vacío para mover
  },
};
