export const board4 = {
  dimension: 4,
  image: 'helice.jpg',
  blankImage: 'image.png',
  time: 90,
  initialTable: {
    0: {
      positionImage: '0% 33.33%',
      focus: false,
      isBlank: false,
      active: false,
      valueExpected: 4,
    },
    1: {
      positionImage: '0% 0%',
      focus: false,
      isBlank: false,
      active: false,
      valueExpected: 0,
    },
    2: {
      positionImage: '66.66% 0%',
      focus: false,
      isBlank: false,
      active: false,
      valueExpected: 2,
    },
    3: {
      positionImage: '100% 0%',
      focus: false,
      isBlank: false,
      active: false,
      valueExpected: 3,
    },
    4: {
      positionImage: '0% 66.66%',
      focus: false,
      isBlank: false,
      active: false,
      valueExpected: 8,
    },
    5: {
      positionImage: '33.33% 0%',
      focus: false,
      isBlank: false,
      active: false,
      valueExpected: 1,
    },
    6: {
      positionImage: '33.33% 33.33%',
      focus: false,
      isBlank: false,
      active: false,
      valueExpected: 5,
    },
    7: {
      positionImage: '66.66% 33.33%',
      focus: false,
      isBlank: false,
      active: false,
      valueExpected: 6,
    },
    8: {
      positionImage: '33.33% 66.66%',
      focus: false,
      isBlank: false,
      active: false,
      valueExpected: 9,
    },
    9: {
      positionImage: '33.33% 100%',
      focus: false,
      isBlank: false,
      active: false,
      valueExpected: 13,
    },
    10: {
      positionImage: '100% 66.66%',
      focus: false,
      isBlank: true,
      active: false,
      valueExpected: 11,
    },
    11: {
      positionImage: '100% 33.33%',
      focus: false,
      isBlank: false,
      active: false,
      valueExpected: 7,
    },
    12: {
      positionImage: '0% 100%',
      focus: false,
      isBlank: false,
      active: false,
      valueExpected: 12,
    },
    13: {
      positionImage: '66.66% 100%',
      focus: false,
      isBlank: false,
      active: false,
      valueExpected: 14,
    },
    14: {
      positionImage: '66.66% 66.66%',
      focus: false,
      isBlank: false,
      active: false,
      valueExpected: 10,
    },
    15: {
      positionImage: '100% 100%',
      focus: false,
      isBlank: false,
      active: false,
      valueExpected: 15,
    },
  },
  table: {
    0: {
      positionImage: '0% 33.33%',
      focus: false,
      isBlank: false,
      active: false,
      valueExpected: 4,
    },
    1: {
      positionImage: '0% 0%',
      focus: false,
      isBlank: false,
      active: false,
      valueExpected: 0,
    },
    2: {
      positionImage: '66.66% 0%',
      focus: false,
      isBlank: false,
      active: false,
      valueExpected: 2,
    },
    3: {
      positionImage: '100% 0%',
      focus: false,
      isBlank: false,
      active: false,
      valueExpected: 3,
    },
    4: {
      positionImage: '0% 66.66%',
      focus: false,
      isBlank: false,
      active: false,
      valueExpected: 8,
    },
    5: {
      positionImage: '33.33% 0%',
      focus: false,
      isBlank: false,
      active: false,
      valueExpected: 1,
    },
    6: {
      positionImage: '33.33% 33.33%',
      focus: false,
      isBlank: false,
      active: false,
      valueExpected: 5,
    },
    7: {
      positionImage: '66.66% 33.33%',
      focus: false,
      isBlank: false,
      active: false,
      valueExpected: 6,
    },
    8: {
      positionImage: '33.33% 66.66%',
      focus: false,
      isBlank: false,
      active: false,
      valueExpected: 9,
    },
    9: {
      positionImage: '33.33% 100%',
      focus: false,
      isBlank: false,
      active: false,
      valueExpected: 13,
    },
    10: {
      positionImage: '100% 66.66%',
      focus: false,
      isBlank: true,
      active: false,
      valueExpected: 11,
    },
    11: {
      positionImage: '100% 33.33%',
      focus: false,
      isBlank: false,
      active: false,
      valueExpected: 7,
    },
    12: {
      positionImage: '0% 100%',
      focus: false,
      isBlank: false,
      active: false,
      valueExpected: 12,
    },
    13: {
      positionImage: '66.66% 100%',
      focus: false,
      isBlank: false,
      active: false,
      valueExpected: 14,
    },
    14: {
      positionImage: '66.66% 66.66%',
      focus: false,
      isBlank: false,
      active: false,
      valueExpected: 10,
    },
    15: {
      positionImage: '100% 100%',
      focus: false,
      isBlank: false,
      active: false,
      valueExpected: 15,
    },
  },
};
