export const board3 = {
  dimension: 3,
  image: 'airplane.jpg',
  blankImage: 'image.png',
  table: {
    0: {
      positionImage: '0% 0%',
      focus: false,
      isBlank: false,
      active: false,
      valueExpected: 0,
    },
    1: {
      positionImage: '50% 0%',
      focus: false,
      isBlank: false,
      active: false,
      valueExpected: 1,
    },
    2: {
      positionImage: '100% 0%',
      focus: false,
      isBlank: false,
      active: false,
      valueExpected: 2,
    },
    3: {
      positionImage: '0% 50%',
      focus: false,
      isBlank: false,
      active: false,
      valueExpected: 3,
    },
    4: {
      positionImage: '50% 50%',
      focus: false,
      isBlank: false,
      active: false,
      valueExpected: 4,
    },
    5: {
      positionImage: '100% 50%',
      focus: false,
      isBlank: false,
      active: false,
      valueExpected: 5,
    },
    6: {
      positionImage: '0% 100%',
      focus: false,
      isBlank: false,
      active: false,
      valueExpected: 6,
    },
    7: {
      positionImage: '50% 100%',
      focus: false,
      isBlank: false,
      active: false,
      valueExpected: 7,
    },
    8: {
      positionImage: '100% 100%',
      focus: false,
      isBlank: true,
      active: false,
      valueExpected: 8,
    },
  },
};
